#ifndef __TASKS_DEBUG_H__
#define __TASKS_DEBUG_H__

#include <debug.hpp>

#define TASKS_SYSTEM_STR "TASKS"
#define TASKS_COLOR_STR COLOR_YELLOW

#ifdef TASKS_DEBUG

#define TASKS_DEBUG_PRINT(fmt, ...) \
    DEBUG_PRINT(TASKS_SYSTEM_STR, TASKS_COLOR_STR, fmt, ##__VA_ARGS__)
#define TASKS_DEBUG_PRINTLN(fmt, ...) \
    DEBUG_PRINTLN(TASKS_SYSTEM_STR, TASKS_COLOR_STR, fmt, ##__VA_ARGS__)
#define TASKS_DEBUG_PRINT_ERROR(fmt, ...) \
    DEBUG_PRINT_ERROR(TASKS_SYSTEM_STR, TASKS_COLOR_STR, fmt, ##__VA_ARGS__)
#define TASKS_DEBUG_PRINT_ERRORLN(fmt, ...) \
    DEBUG_PRINT_ERRORLN(TASKS_SYSTEM_STR, TASKS_COLOR_STR, fmt, ##__VA_ARGS__)
#define TASKS_DEBUG_PRINT_FATAL_ERROR(fmt, ...) \
    DEBUG_PRINT_FATAL_ERROR(TASKS_SYSTEM_STR, TASKS_COLOR_STR, fmt, ##__VA_ARGS__)
#define TASKS_DEBUG_PRINT_FATAL_ERRORLN(fmt, ...) \
    DEBUG_PRINT_FATAL_ERRORLN(TASKS_SYSTEM_STR, TASKS_COLOR_STR, fmt, ##__VA_ARGS__)

#else  // TASKS_DEBUG

#define TASKS_DEBUG_PRINT(fmt, ...) (void)0
#define TASKS_DEBUG_PRINTLN(fmt, ...) (void)0
#define TASKS_DEBUG_PRINT_ERROR(fmt, ...) (void)0
#define TASKS_DEBUG_PRINT_ERRORLN(fmt, ...) (void)0
#define TASKS_DEBUG_PRINT_FATAL_ERROR(fmt, ...) (void)0
#define TASKS_DEBUG_PRINT_FATAL_ERRORLN(fmt, ...) (void)0

#endif

#endif  // __TASKS_DEBUG_H__