#ifndef __REMOTE_DEBUG_H__
#define __REMOTE_DEBUG_H__

#include <debug.hpp>

#define REMOTE_SYSTEM_STR "REMOTE"
#define REMOTE_COLOR_STR COLOR_MAGENTA

#ifdef REMOTE_DEBUG

#define REMOTE_DEBUG_PRINT(fmt, ...) \
    DEBUG_PRINT(REMOTE_SYSTEM_STR, REMOTE_COLOR_STR, fmt, ##__VA_ARGS__)
#define REMOTE_DEBUG_PRINTLN(fmt, ...) \
    DEBUG_PRINTLN(REMOTE_SYSTEM_STR, REMOTE_COLOR_STR, fmt, ##__VA_ARGS__)
#define REMOTE_DEBUG_PRINT_ERROR(fmt, ...) \
    DEBUG_PRINT_ERROR(REMOTE_SYSTEM_STR, REMOTE_COLOR_STR, fmt, ##__VA_ARGS__)
#define REMOTE_DEBUG_PRINT_ERRORLN(fmt, ...) \
    DEBUG_PRINT_ERRORLN(REMOTE_SYSTEM_STR, REMOTE_COLOR_STR, fmt, ##__VA_ARGS__)
#define REMOTE_DEBUG_PRINT_FATAL_ERROR(fmt, ...) \
    DEBUG_PRINT_FATAL_ERROR(REMOTE_SYSTEM_STR, REMOTE_COLOR_STR, fmt, ##__VA_ARGS__)
#define REMOTE_DEBUG_PRINT_FATAL_ERRORLN(fmt, ...) \
    DEBUG_PRINT_FATAL_ERRORLN(REMOTE_SYSTEM_STR, REMOTE_COLOR_STR, fmt, ##__VA_ARGS__)

#else  // REMOTE_DEBUG

#define REMOTE_DEBUG_PRINT(fmt, ...) (void)0
#define REMOTE_DEBUG_PRINTLN(fmt, ...) (void)0
#define REMOTE_DEBUG_PRINT_ERROR(fmt, ...) (void)0
#define REMOTE_DEBUG_PRINT_ERRORLN(fmt, ...) (void)0
#define REMOTE_DEBUG_PRINT_FATAL_ERROR(fmt, ...) (void)0
#define REMOTE_DEBUG_PRINT_FATAL_ERRORLN(fmt, ...) (void)0

#endif

#endif  // __REMOTE_DEBUG_H__